# Generated by Django 5.1.3 on 2024-11-15 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('1', 'Data Collection'), ('2', 'Data Recieved'), ('3', 'Data Process / Working'), ('4', 'Approval From Sir'), ('5', 'Approval From Client'), ('6', 'Challan Sent'), ('7', 'Challan Paid')], max_length=128)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('mode_of_payment', models.CharField(blank=True, max_length=128, null=True)),
                ('status_description', models.TextField(blank=True, null=True)),
                ('project_completed', models.BooleanField(default=False)),
                ('Document_endpath', models.CharField(max_length=128)),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.client')),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.department')),
                ('Employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.employee')),
            ],
        ),
    ]
