# Generated by Django 5.1.4 on 2025-03-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_project_client_alter_project_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='pan',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
