# Generated by Django 5.1.3 on 2024-11-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_project_document_endpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(choices=[('Advance Tax', 'Advance Tax'), ('GSTR1', 'GSTR1')], max_length=128),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(max_length=128),
        ),
    ]
