# Generated by Django 5.1.4 on 2025-03-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_client_pan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='pan',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
