# Generated by Django 5.1.3 on 2024-11-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_project_name_alter_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='period',
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Advance Tax', 'Advance Tax'), ('GSTR1', 'GSTR1')], default=0.5217391304347826, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
