# Generated by Django 5.1.4 on 2025-06-13 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_task_custom_status_alter_project_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(blank=True, choices=[('Advance Tax', [('Data Collection', 'Data Collection'), ('Data Recieved', 'Data Recieved'), ('Data Process / Working', 'Data Process / Working'), ('Approval From Sir', 'Approval From Sir'), ('Approval From Client', 'Approval From Client'), ('Challan Sent', 'Challan Sent'), ('Challan Paid', 'Challan Paid')]), ('GSTR1', [('Follow Up for Data', 'Follow Up for Data'), ('Data Recieved', 'Data Recieved'), ('Processing of Data', 'Processing of Data'), ('Query Sent To Client', 'Query Sent To Client'), ('Query Solve From Client', 'Query Sent From Client'), ('After solving of Query Tax Power Feeding ', 'After solving of Query Tax Power Feeding '), ('Checking Done By Head', 'Checking Done By Head'), ('Uploading', 'Uploading')]), ('GSTR3B', [('Download and Sent 2B Report', 'Download and Sent 2B Report'), ('Follow Up For Data', 'Follow Up For Data'), ('Data Recieved and Processing of Data', 'Data Recieved and Processing of Data'), ('Query Sent To Client & Query Solve From Client', 'Query Sent To Client & Query Solve From Client'), ('After Solving of Query Tax Power Feeding', 'After Solving of Query Tax Power Feeding'), ('Checking Done By Head', 'Checking Done By Head'), ('Challan Sent to Client & Follow Up for Payment', 'Challan Sent to Client & Follow Up for Payment'), ('Checking For Payment Status Whether Paid Or Not', 'Checking For Payment Status Whether Paid Or Not'), ('After Making Of Payment Submit the Return', 'After Making Of Payment Submit the Return'), ('Uploading', 'Uploading')]), ('Income Tax Return (Audit)', [('Getting Uploaded Copy of Audit Report', 'Getting Uploaded Copy of Audit Report'), ('Data collection of Personal of Prop .,/Partners etc', 'Data collection of Personal of Prop .,/Partners etc'), ('Queries Raised', 'Queries Raised'), ('Queries Solved', 'Queries Solved'), ('Data Entry in Software', 'Data Entry in Software'), ('Client confirmation for SA ,Income etc', 'Client confirmation for SA ,Income etc'), ('Checking before Filing', 'Checking before Filing'), ('Uploaded', 'Uploaded'), ('Bill Preparation & Sending to Client', 'Bill Preparation & Sending to Client'), ('Completion Report to DMM', 'Completion Report to DMM'), ('Rectification Return , if any', 'Rectification Return , if any')]), ('Income Tax Return (Non-Audit)', [('Data Collection', 'Data Collection'), ('Data Process', 'Data Process'), ('Queries Raised', 'Queries Raised'), ('Queries Solved', 'Queries Solved'), ('Data Entry in Software', 'Data Entry in Software'), ('Client confirmation for SA ,Income etc', 'Client confirmation for SA ,Income etc'), ('Checking before Filing', 'Checking before Filing'), ('Uploaded', 'Uploaded'), ('Bill Preparation & Sending to Client', 'Bill Preparation & Sending to Client'), ('Completion Report to DMM', 'Completion Report to DMM'), ('Rectification Return , if any', 'Rectification Return , if any')]), ('TDS', [('Data Collection', 'Data Collection'), ('Data Process', 'Data Process'), ('Queries Raised', 'Queries Raised'), ('Queries Solved', 'Queries Solved'), ('Data Entry in Software', 'Data Entry in Software'), ('Challan Prepared & Given', 'Challan Prepared & Given'), ('Data Collection', 'Data Collection'), ('Data Process', 'Data Process'), ('Working Prepared', 'Working Prepared'), ('Queries Raised', 'Queries Raised'), ('Queries Solved', 'Queries Solved'), ('Paid Challan Received', 'Paid Challan Received'), ('Data Entry in Software', 'Data Entry in Software'), ('Uploaded', 'Uploaded'), ('Completion Report to DMM', 'Completion Report to DMM')]), ('GSTR 2A/2B', [('Data Collection', 'Data Collection'), ('Data Process', 'Data Process'), ('Queries Raised', 'Queries Raised'), ('Queries Solved', 'Queries Solved'), ('Data Entry in Software', 'Data Entry in Software'), ('Client confirmation in case of 2B', 'Client confirmation in case of 2B'), ('Checking by HOD', 'Checking by HOD'), ('Uploaded', 'Uploaded'), ('Completion Report to DMM', 'Completion Report to DMM'), ('Amendments ,if any', 'Amendments ,if any')])], max_length=126, null=True),
        ),
        migrations.AlterField(
            model_name='totp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
