# Generated by Django 5.1.3 on 2024-11-21 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_project_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
    ]
