name: Keep Render Server Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minute
  workflow_dispatch:       # Allows manual trigger from GitHub Actions tab

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send request to Render server
        run: curl -s https://dmm-server.onrender.com
